# Generated by Django 4.2 on 2026-07-01 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='room_no',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
