# Generated by Django 4.2 on 2026-07-02 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_facility_rooms_review_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='room_image')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image', to='app1.rooms')),
            ],
        ),
    ]
