# Generated by Django 4.2 on 2026-07-04 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_alter_image_photo_alter_image_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='rooms',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
