# Generated by Django 4.2 on 2026-07-09 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_rooms_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='room_price',
            field=models.ImageField(default=0, upload_to=''),
            preserve_default=False,
        ),
    ]
