# Generated by Django 4.2 on 2026-07-09 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_booking_room_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='room_no',
            field=models.IntegerField(null=True),
        ),
    ]
